### ISSUE TITLE
Database Patching... (blank screen at startup)

### ISSUE THREAD

**Issue by tiotrom** [librats/rats-search#105]
I get the following errors using the appimage:

```
(rats-search:10224): Gtk-WARNING **: 15:35:03.154: Theme parsing error: gtk.css:2:112: Failed to import: Error opening file /home/tio/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet.css: No such file or directory

(rats-search:10224): Gtk-WARNING **: 15:35:03.154: Theme parsing error: gtk.css:3:118: Failed to import: Error opening file /home/tio/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet-tiled.css: No such file or directory
[system] Rats 1.4.0
[system] Platform: linux
[system] Arch: x64
[system] OS Release: 4.19.84-1-MANJARO
[system] CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
[system] CPU Logic cores: 8
[system] Total memory: 32052.48 MB
[system] Free memory: 21362.49 MB
[system] NodeJS: v12.4.0
[system] Desktop server
(node:10224) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:10224) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[udp-tracker] listening udp tracker respose on 0.0.0.0:4446
[sphinx] Sphinx Path: /opt/rats-search-git/x64/searchd
[sphinx] writed sphinx config to /home/tio/.config/Rats on The Boat
[sphinx] db path: /home/tio/.config/Rats on The Boat
[sphinx] sphinx: [Fri Nov 22 15:35:03.746 2019] [10259] using config file '/home/tio/.config/Rats on The Boat/sphinx.conf'...
listening on 127.0.0.1:9313
listening on 127.0.0.1:9307
Manticore 2.6.1 a7fa71e@180126 release
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2018, Manticore Software LTD (http://manticoresearch.com)

precaching index 'torrents'

[sphinx] sphinx: precaching index 'files'

[sphinx] sphinx: precaching index 'version'
precaching index 'store'

[sphinx] sphinx: precaching index 'feed'

[sphinx] sphinx: accepting connections
prereading 5 indexes

[sphinx] catched sphinx start
[sphinx] sphinx: prereaded 5 indexes in 0.000 sec

[patcher] db version 4
[sphinx] sphinx closing...
[sphinx] sphinx: caught SIGTERM, shutting down

[sphinx] sphinx: rt: index torrents: ramchunk saved in 0.005 sec

[sphinx] sphinx: shutdown complete

[sphinx] sphinx: precached 5 indexes in 0.003 sec

[sphinx] sphinx closed with code 0 and signal null
[patcher] sphinx stoped for patching
[patcher] clear torrents file /home/tio/.config/Rats on The Boat/database/torrents.kill
[patcher] clear torrents file /home/tio/.config/Rats on The Boat/database/torrents.lock
[patcher] clear torrents file /home/tio/.config/Rats on The Boat/database/torrents.meta
[patcher] clear torrents file /home/tio/.config/Rats on The Boat/database/torrents.ram
[patcher] cleaned torrents db structure, rectreating again
[sphinx] Sphinx Path: /opt/rats-search-git/x64/searchd
[sphinx] writed sphinx config to /home/tio/.config/Rats on The Boat
[sphinx] db path: /home/tio/.config/Rats on The Boat
[sphinx] sphinx: [Fri Nov 22 15:35:03.975 2019] [10289] using config file '/home/tio/.config/Rats on The Boat/sphinx.conf'...

[sphinx] sphinx: listening on 127.0.0.1:9313
listening on 127.0.0.1:9307

[sphinx] sphinx: Manticore 2.6.1 a7fa71e@180126 release
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2018, Manticore Software LTD (http://manticoresearch.com)

precaching index 'torrents'

[sphinx] sphinx: precaching index 'files'
precaching index 'version'
precaching index 'store'

[sphinx] sphinx: precaching index 'feed'

[sphinx] sphinx: accepting connections
prereading 5 indexes

[sphinx] catched sphinx start
[sphinx] sphinx: prereaded 5 indexes in 0.000 sec

[patcher] sphinx restarted, patch db now
[patcher] optimizing torrents
[system] Rejection: TypeError: s.waitOptimized is not a function
    at g (/opt/rats-search-git/resources/app.asar/app/background.js:1:107506)
    at async g (/opt/rats-search-git/resources/app.asar/app/background.js:1:109307)
[sphinx] sphinx: rt: index torrents: optimized (progressive) chunk(s) 0 ( of 0 ) in 0.000 sec
```

**Comment by SpekFox** [comment]
me too, long "Database patching..." after update on new version.

**Comment by kevinmitnik** [comment]
+1

**Comment by kknstv** [comment]
Deleting a folder (`c:\Users\{usr}\AppData\Roaming\Rats on The Boat\`) helps, but the base will be lost. 
Perhaps you can slip it back, I have not tested

**Comment by DEgITx** [comment]
such module no in 2.x, 1.x unsupported
