### ISSUE TITLE
When the website service runs for half an hour to an hour, errors may occur

### ISSUE THREAD

**Issue by RickHunterS** [librats/rats-search#140]
Hello, when I run the website service on the server for about half an hour to an hour, the following error will appear, and then the Linux terminal will automatically “killed ” the process. Can you help me find out the cause of my mistake.

[system] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/root/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/root/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/root/rats-search/node_modules/mysql/lib/Connection.js:198:25)
    at queryCall (/root/rats-search/src/background/mysql.js:12:10)
    at Promise (/root/rats-search/src/background/mysql.js:30:4)
    at new Promise (<anonymous>)
    at Connection.sphinx.query (/root/rats-search/src/background/mysql.js:15:42)
    at Promise (/root/rats-search/src/background/spider.js:621:17)
    at new Promise (<anonymous>)
    at insertTorrentToDB (/root/rats-search/src/background/spider.js:542:50) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }

[spider] finded torrent The.Godfather.Part.II.1974.576p.BRRip.x265-DiN and add to database
[add] { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/root/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/root/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/root/rats-search/node_modules/mysql/lib/Connection.js:198:25)
    at queryCall (/root/rats-search/src/background/mysql.js:12:10)
    at Promise (/root/rats-search/src/background/mysql.js:30:4)
    at new Promise (<anonymous>)
    at Connection.sphinx.query (/root/rats-search/src/background/mysql.js:15:42)
    at Promise (/root/rats-search/src/background/spider.js:621:17)
    at new Promise (<anonymous>)
    at insertTorrentToDB (/root/rats-search/src/background/spider.js:542:50) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }

[system] Rejection: { Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/root/rats-search/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/root/rats-search/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/root/rats-search/node_modules/mysql/lib/Connection.js:198:25)
    at queryCall (/root/rats-search/src/background/mysql.js:12:10)
    at Promise (/root/rats-search/src/background/mysql.js:30:4)
    at new[root@racknerd-acba13 rats-search]# Promise (<anonymous>)
    at Connection.sphinx.query (/root/rats-search/src/background/mysql.js:15:42)
    at Promise (/root/rats-search/src/background/spider.js:621:17)
    at new Promise (<anonymous>)
    at insertTorrentToDB (/root/rats-search/src/background/spider.js:542:50) code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }

Killed
[root@racknerd-acba13 rats-search]#

**Comment by RickHunterS** [comment]
Oh, yes, about the last question how to keep the background running, the current solution I use is to use TMUX, create a new session, and then exit to separate the session from the background running

**Comment by DEgITx** [comment]
can you recheck with master? and post rats.log

**Comment by DEgITx** [comment]
not actuall anymore, in 2.0 changed
