### ISSUE TITLE
Server mode падает on Debian Stretch

### ISSUE THREAD

**Issue by SpcCw** [librats/rats-search#77]
rats-search v1.1.3
node -v - v10.15.1
npm -v 6.4.1

Выпадает примерно раз в час-два вне зависимости от настроек, сейчас стоит 5/100/100. Ставил радикально больше-меньше, зависимости с вылетами пока не обнаружил, только разная нагрузка на процессор и роутер.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'server' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle rats-search@1.1.2~preserver: rats-search@1.1.2
6 info lifecycle rats-search@1.1.2~server: rats-search@1.1.2
7 verbose lifecycle rats-search@1.1.2~server: unsafe-perm in lifecycle true
8 verbose lifecycle rats-search@1.1.2~server: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rat/rats-search/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle rats-search@1.1.2~server: CWD: /home/rat/rats-search
10 silly lifecycle rats-search@1.1.2~server: Args: [ '-c', 'node src/background/server.js' ]
11 silly lifecycle rats-search@1.1.2~server: Returned: code: 134  signal: null
12 info lifecycle rats-search@1.1.2~server: Failed to exec server script
13 verbose stack Error: rats-search@1.1.2 server: `node src/background/server.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid rats-search@1.1.2
15 verbose cwd /home/rat/rats-search
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 134
22 error rats-search@1.1.2 server: `node src/background/server.js`
22 error Exit status 134
23 error Failed at the rats-search@1.1.2 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

Поставил службой с автоматическим перезапуском, но если есть рекомендации, буду рад :)

**Comment by DEgITx** [comment]
Прикрепите rats.log, но в целом там есть один известный баг, когда будет поправлен, думаю лучше будет.

**Comment by SpcCw** [comment]
А где взять rats.log? :)

Есть searchd.log с содержимым вида:
```
[Tue Feb 12 06:30:52.167 2019] [5066] listening on 127.0.0.1:9312
[Tue Feb 12 06:30:52.167 2019] [5066] listening on 127.0.0.1:9306
[Tue Feb 12 06:30:52.281 2019] [5066] accepting connections
[Tue Feb 12 06:30:52.281 2019] [5074] prereading 5 indexes
[Tue Feb 12 06:30:52.281 2019] [5074] prereaded 5 indexes in 0.000 sec
[Tue Feb 12 07:38:15.746 2019] [5066] caught SIGTERM, shutting down
[Tue Feb 12 07:38:16.074 2019] [5066] rt: index torrents: ramchunk saved in 0.246 sec
[Tue Feb 12 07:38:16.547 2019] [5066] rt: index files: ramchunk saved in 0.472 sec
[Tue Feb 12 07:38:16.548 2019] [5066] rt: index version: ramchunk saved in 0.001 sec
[Tue Feb 12 07:38:16.579 2019] [5066] rt: index feed: ramchunk saved in 0.029 sec
[Tue Feb 12 07:38:16.579 2019] [5066] shutdown complete
```
Ещё есть вывод в консоль. rats.log не нашёл.

**Comment by SpcCw** [comment]
Обновление: на текущий момент с последними версиями всего ROTB 1.2.2 падает один-два раза в сутки. Почему-то чаще по ночам :) В принципе, для серверного режима не критично, поставил перезапуск автоматически через 60 секунд и не замечаю.

P.S. Музыка отличная! Пишите ещё :)

**Comment by DEgITx** [comment]
перепроверь плиз в 2.x, 1.x больше не поддерживается
